[package]
name = "identify-ports"
description = "This crate contains abstract interfaces required for Identify to function"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
identify-domain = { workspace = true }
uuid = { workspace = true }
async-trait = { workspace = true }

[lints]
workspace = true
